#!/bin/zsh

code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.bookmarks
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension christian-kohler.npm-intellisense
code --install-extension codezombiech.gitignore
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension elagil.pre-commit-helper
code --install-extension ericsia.pythonsnippets3
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension golang.go
code --install-extension hashicorp.hcl
code --install-extension hashicorp.terraform
code --install-extension humao.rest-client
code --install-extension jianglinghao.vscode-npm-scripts
code --install-extension jock.svg
code --install-extension mechatroner.rainbow-csv
code --install-extension meganrogge.template-string-converter
code --install-extension mohsen1.prettify-json
code --install-extension mongodb.mongodb-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.flake8
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension naumovs.color-highlight
code --install-extension njpwerner.autodocstring
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension phplasma.csv-to-table
code --install-extension poeticandroid.vscode-poetry
code --install-extension prisma.prisma
code --install-extension rangav.vscode-thunder-client
code --install-extension redhat.ansible
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension rust-lang.rust-analyzer
code --install-extension sdras.night-owl
code --install-extension sdras.vue-vscode-snippets
code --install-extension sonarsource.sonarlint-vscode
code --install-extension svelte.svelte-vscode
code --install-extension syler.sass-indented
code --install-extension tobermory.es6-string-html
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension vscodevim.vim
code --install-extension vue.volar
code --install-extension wakatime.vscode-wakatime
code --install-extension wallabyjs.quokka-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension wmaurer.vscode-jumpy
code --install-extension xabikos.javascriptsnippets